'use client'

import { FormEvent, useState } from 'react'
import { ArrowRight, BarChart3, Check, ChevronRight, Eye, Gauge, Menu, ShieldCheck, Sparkles, Target, X } from 'lucide-react'

const channels=['Meta ads','Google ads','Creators','Social content','WhatsApp','Events & offline']
const gaps=[
 ['Spend is visible. Customers are not.','Platforms report clicks, reach and leads. Your business needs to know what became an enquiry, visit, sale or repeat customer.'],
 ['Every platform claims success.','Google, Meta, agencies and sales teams can all tell different stories about the same customer journey.'],
 ['Historical data is hard to trust.','Missing source fields, anonymous walk-ins and inconsistent follow-up make perfect attribution impossible after the fact.']
]

export default function Page(){
 const[open,setOpen]=useState(false)
 const[status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle')
 const[form,setForm]=useState({name:'',business:'',website:'',email:'',phone:'',campaign:'',company:''})
 const update=(key:string,value:string)=>setForm({...form,[key]:value})
 const submit=async(e:FormEvent)=>{e.preventDefault();if(form.company)return;setStatus('loading');try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,service:'Campaign Proof Review',message:`Upcoming campaign or marketing challenge: ${form.campaign}`})});if(!res.ok)throw new Error();setStatus('success')}catch{setStatus('error')}}
 return <div className="fb-site">
  <header className="fb-header"><div className="fb-shell fb-nav"><a className="fb-brand" href="#top"><span>F</span>Fameboat</a><nav className="fb-desktop"><a href="#problem">The problem</a><a href="#how">How it works</a><a href="#proof">Campaign Proof</a><a href="#about">Why Fameboat</a></nav><a className="fb-btn fb-btn-dark fb-desktop" href="#review">Make my next campaign measurable</a><button className="fb-menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div>{open&&<div className="fb-mobile"><a href="#problem" onClick={()=>setOpen(false)}>The problem</a><a href="#how" onClick={()=>setOpen(false)}>How it works</a><a href="#proof" onClick={()=>setOpen(false)}>Campaign Proof</a><a className="fb-btn fb-btn-dark" href="#review" onClick={()=>setOpen(false)}>Make my next campaign measurable</a></div>}</header>

  <main id="top">
   <section className="fb-hero"><div className="fb-shell fb-hero-grid"><div><h1>Know what is actually bringing customers.</h1><p className="fb-lead">Fameboat helps businesses make marketing accountable—connecting campaigns with real enquiries, visits and sales, without demanding sensitive data on day one.</p><div className="fb-actions"><a className="fb-btn fb-btn-primary" href="#review">Review my next campaign <ArrowRight size={18}/></a><a className="fb-text-link" href="#how">See how it works <ChevronRight size={17}/></a></div><p className="fb-trustline"><ShieldCheck size={16}/> No passwords. No CRM migration. No customer database required to begin.</p></div><MeasurementPreview/></div></section>

   <section className="fb-signal"><div className="fb-shell"><p>Marketing activity is everywhere. Business proof is still missing.</p><div>{channels.map(x=><span key={x}>{x}</span>)}</div></div></section>

   <section id="problem" className="fb-section"><div className="fb-shell"><div className="fb-section-head"><h2>You know what you spent. But can you prove what created business?</h2><p>Reach, clicks and leads are useful signals. They are not the same as customers, revenue or incremental growth.</p></div><div className="fb-gap-list">{gaps.map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

   <section id="how" className="fb-section fb-dark"><div className="fb-shell"><div className="fb-section-head fb-light"><h2>Start with one campaign. Build proof before the money is spent.</h2><p>Fameboat does not ask you to rebuild your business. We make one upcoming campaign measurable, learn what the evidence says, and improve from there.</p></div><div className="fb-steps">
    <Step n="01" icon={<Eye/>} title="Review" text="We examine the public customer journey, current marketing touchpoints and what can or cannot be measured today."/>
    <Step n="02" icon={<Target/>} title="Design" text="We define the business outcome, source capture, campaign links, WhatsApp paths, offer codes and practical success thresholds."/>
    <Step n="03" icon={<Gauge/>} title="Measure" text="We compare campaign signals with enquiries, visits, sales or another real commercial outcome—using only the access you approve."/>
    <Step n="04" icon={<BarChart3/>} title="Decide" text="You receive a plain-English view of what worked, what remains uncertain, what to stop and what to test next."/>
   </div></div></section>

   <section id="proof" className="fb-section"><div className="fb-shell fb-proof-grid"><div><h2>Fameboat Campaign Proof</h2><p className="fb-lead-small">A focused engagement to make your next marketing investment more measurable from the start.</p><div className="fb-checks">{['Measurement-readiness review','One clearly defined business outcome','Trackable campaign touchpoints','Simple customer-source capture','Campaign-to-outcome scorecard','Continue, stop or test-next recommendation'].map(x=><p key={x}><Check size={17}/>{x}</p>)}</div><a className="fb-btn fb-btn-primary" href="#review">Discuss an upcoming campaign <ArrowRight size={18}/></a></div><div className="fb-proof-card"><span className="fb-card-label">What the owner receives</span><div className="fb-proof-row"><span>What we know</span><strong>High-confidence outcomes</strong></div><div className="fb-proof-row"><span>What we estimate</span><strong>Likely influence and gaps</strong></div><div className="fb-proof-row"><span>What to test</span><strong>The next measurable experiment</strong></div><div className="fb-decision"><Sparkles size={19}/><div><small>Decision example</small><strong>Keep Google local. Pause two creator spends. Retest the weekend offer with a unique code.</strong></div></div></div></div></section>

   <section className="fb-section fb-soft"><div className="fb-shell"><div className="fb-section-head"><h2>Useful before connectors. Stronger after trust is earned.</h2><p>We begin with public touchpoints and aggregate numbers. Deeper account connections are optional and introduced only when they add proven value.</p></div><div className="fb-access"><article><span>Level 0</span><h3>Public journey</h3><p>Website, social pages, Google presence, landing paths and visible customer experience.</p></article><article><span>Level 1</span><h3>Business totals</h3><p>Approximate spend, enquiries, visits, customers and revenue—without customer-level records.</p></article><article><span>Level 2</span><h3>Read-only proof</h3><p>Approved reports or official connections when the business is ready for deeper measurement.</p></article></div></div></section>

   <section id="about" className="fb-section"><div className="fb-shell fb-founder"><div className="fb-years">20<span>+</span></div><div><h2>Built from marketing experience—not dashboard theory.</h2><p>Fameboat brings together marketing, branding, media, physical and digital touchpoints, customer journeys and practical technology implementation.</p><p>That matters because the question is not simply which platform produced a click. It is how people discovered, trusted, contacted and finally chose the business.</p></div></div></section>

   <section id="review" className="fb-section fb-review"><div className="fb-shell fb-review-grid"><div><h2>Make the next campaign easier to prove.</h2><p>Share the business and upcoming marketing activity. Fameboat will identify the most practical first measurement approach—without asking for passwords or sensitive customer data.</p></div>{status==='success'?<div className="fb-success"><Check/><h3>Request received.</h3><p>Fameboat will review the information and contact you about the most practical next step.</p></div>:<form onSubmit={submit} className="fb-form"><input className="fb-honeypot" value={form.company} onChange={e=>update('company',e.target.value)} tabIndex={-1} autoComplete="off"/><label>Name<input required value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Business name<input required value={form.business} onChange={e=>update('business',e.target.value)}/></label><label>Website or public page<input type="url" value={form.website} onChange={e=>update('website',e.target.value)}/></label><label>Email<input required type="email" value={form.email} onChange={e=>update('email',e.target.value)}/></label><label>Phone / WhatsApp<input required value={form.phone} onChange={e=>update('phone',e.target.value)}/></label><label className="fb-full">What are you planning to promote?<textarea rows={4} required value={form.campaign} onChange={e=>update('campaign',e.target.value)} placeholder="A new outlet, festive campaign, Meta ads, creator collaboration, product launch…"/></label>{status==='error'&&<p className="fb-error">The request could not be submitted. Please try again.</p>}<button className="fb-btn fb-btn-primary fb-full" disabled={status==='loading'}>{status==='loading'?'Submitting…':'Request a Campaign Proof review'} <ArrowRight size={18}/></button></form>}</div></section>
  </main>
  <footer className="fb-footer"><div className="fb-shell fb-footer-grid"><div><a className="fb-brand fb-brand-light" href="#top"><span>F</span>Fameboat</a><p>Making marketing investment easier to understand, measure and improve.</p></div><div><a href="#problem">The problem</a><a href="#how">How it works</a><a href="#proof">Campaign Proof</a><a href="/privacy">Privacy</a></div></div><div className="fb-shell fb-copy">© 2026 Fameboat</div></footer>
 </div>
}

function Step({n,icon,title,text}:{n:string,icon:React.ReactNode,title:string,text:string}){return <article><div><span>{n}</span>{icon}</div><h3>{title}</h3><p>{text}</p></article>}

function MeasurementPreview(){return <div className="fb-preview"><div className="fb-preview-head"><span>Campaign proof preview</span><em>Illustrative</em></div><div className="fb-preview-spend"><small>Marketing spend reviewed</small><strong>₹1,20,000</strong></div><div className="fb-preview-bars"><div><span>Google local</span><i><b style={{width:'82%'}}/></i><strong>Strong signal</strong></div><div><span>Meta</span><i><b style={{width:'56%'}}/></i><strong>Needs outcome link</strong></div><div><span>Creators</span><i><b style={{width:'28%'}}/></i><strong>Low confidence</strong></div></div><div className="fb-preview-bottom"><div><small>Business outcomes linked</small><strong>38</strong></div><div><small>Spend needing a better test</small><strong>₹34k</strong></div></div></div>}
