"use client"

import Link from "next/link"
import { FormEvent, useState } from "react"
import { ArrowRight, BadgeCheck, BarChart3, CircleHelp, Eye, Lightbulb, MapPin, MessageCircle, Search, ShieldCheck, Sparkles, Target, TrendingUp } from "lucide-react"
import "./fameboat2.css"

const steps=[{icon:Search,title:"Gather",copy:"See the activity and business signals you already have."},{icon:Eye,title:"Connect",copy:"Follow the customer journey from attention to outcome."},{icon:CircleHelp,title:"Clarify",copy:"Separate what the evidence shows from what is still assumed."},{icon:Target,title:"Decide",copy:"Choose what to scale, stop, fix or test next."}]
const situations=[{icon:TrendingUp,text:"You are spending on marketing but are not sure what is working."},{icon:MessageCircle,text:"Leads are coming in but business is not growing proportionately."},{icon:BarChart3,text:"Different channels report different versions of success."},{icon:MapPin,text:"Opportunities may be getting lost between enquiry and sale."}]

export default function Home(){
 const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle")
 const [message,setMessage]=useState("")
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault(); if(status==="sending")return
  const formElement=e.currentTarget; const payload=Object.fromEntries(new FormData(formElement).entries())
  setStatus("sending");setMessage("")
  try{const res=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,service:"14-Day Marketing Proof Audit"})});const data=await res.json();if(!res.ok)throw new Error(data.error);formElement.reset();setStatus("success");setMessage("Thanks — your paid audit request is in. We’ll be in touch shortly.")}catch(err){setStatus("error");setMessage(err instanceof Error?err.message:"Something went wrong. Please try again.")}}
 return <main className="fb3" id="top">
  <header className="fb3-header"><a className="fb3-brand" href="#top"><span>F</span>Fameboat</a><nav><a href="#how">How it works</a><Link href="/proof-lab">Proof Lab</Link><a href="#audit">14-Day Audit</a></nav><a className="fb3-nav-cta" href="#audit">Start audit <ArrowRight size={15}/></a></header>
  <section className="fb3-hero"><div className="fb3-wrap fb3-hero-grid"><div><p className="fb3-label">FAMEBOAT</p><h1>Marketing shows activity.<br/><em>Fameboat shows proof.</em></h1><p className="fb3-lede">A clear view of what looks promising, what remains unclear, and what deserves your attention before you spend more.</p><div className="fb3-actions"><a className="fb3-primary" href="#audit">Start 14-Day Audit <span>₹5,000</span><ArrowRight size={17}/></a><Link className="fb3-secondary" href="/proof-lab">See Fameboat in action</Link></div><p className="fb3-reassure"><ShieldCheck size={16}/>Focused 14-day engagement · Real business data · Clear next decisions</p></div><div className="fb3-question"><div className="fb3-question-icon"><Eye size={32}/></div><p>ONE BETTER QUESTION</p><strong>What is actually creating business?</strong><span>Start with the evidence you have, not a perfect dashboard.</span></div></div></section>
  <section className="fb3-problem"><div className="fb3-wrap"><div className="fb3-section-head"><div><p className="fb3-label">THE PROBLEM</p><h2>Lots of activity.<br/>Not enough clarity.</h2></div><p>Clicks, leads, followers, calls, messages, traffic and campaign reports can all look busy — without telling you what changed the business.</p></div><div className="fb3-signal-grid">{[{icon:Eye,label:"Visible",copy:"Activity is easy to see."},{icon:CircleHelp,label:"Unclear",copy:"Contribution is harder to prove."},{icon:Lightbulb,label:"Missed",copy:"Opportunities can disappear in the journey."},{icon:Target,label:"Needed",copy:"A better next decision."}].map(({icon:Icon,label,copy})=><article key={label}><Icon/><div><strong>{label}</strong><span>{copy}</span></div></article>)}</div></div></section>
  <section className="fb3-how" id="how"><div className="fb3-wrap"><p className="fb3-label">HOW IT WORKS</p><h2>From activity to a decision.</h2><div className="fb3-steps">{steps.map(({icon:Icon,title,copy},i)=><article key={title}><div><span>0{i+1}</span><Icon size={25}/></div><h3>{title}</h3><p>{copy}</p>{i<steps.length-1&&<ArrowRight className="fb3-step-arrow" size={20}/>}</article>)}</div></div></section>
  <section className="fb3-lab"><div className="fb3-wrap fb3-lab-inner"><div className="fb3-lab-mark"><Sparkles size={33}/></div><div><p className="fb3-label">PROOF LAB</p><h2>See what Fameboat notices.</h2><p>Answer a few simple questions. Get an honest, client-side first view in about a minute.</p></div><Link className="fb3-primary" href="/proof-lab">Open Proof Lab <ArrowRight size={17}/></Link></div></section>
  <section className="fb3-audit" id="audit"><div className="fb3-wrap"><div className="fb3-audit-top"><div><p className="fb3-label">THE 14-DAY AUDIT</p><h2>14 days to focus on what matters.</h2></div><div className="fb3-price"><span>Focused paid engagement</span><strong>₹5,000</strong></div></div><div className="fb3-timeline">{[["1–2","Frame the business question"],["3–5","Review available evidence"],["6–9","Find gaps and patterns"],["10–12","Investigate the opportunity"],["13–14","Share clear next moves"]].map(([day,copy],i)=><article key={day}><span>{i+1}</span><b>Days {day}</b><p>{copy}</p></article>)}</div></div></section>
  <section className="fb3-value"><div className="fb3-wrap"><div className="fb3-section-head"><div><p className="fb3-label">WHAT YOU GET</p><h2>Useful evidence.<br/>A clearer next move.</h2></div><p>Not a huge report for appearance. A concise, practical summary to help you decide what to do next.</p></div><div className="fb3-deliverables">{[{icon:CircleHelp,t:"Business question",c:"Define what needs to be understood."},{icon:Search,t:"Channel review",c:"See the marketing signals available."},{icon:MapPin,t:"Journey view",c:"Find where momentum may be lost."},{icon:BadgeCheck,t:"Decision summary",c:"Scale, stop, fix or test next."}].map(({icon:Icon,t,c})=><article key={t}><Icon/><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
  <section className="fb3-fit"><div className="fb3-wrap fb3-fit-grid"><div><p className="fb3-label">THIS MAY BE USEFUL IF…</p><h2>You need a clearer view before the next spend.</h2><p>You don’t need perfect data to start.</p></div><div>{situations.map(({icon:Icon,text})=><p key={text}><Icon size={19}/>{text}</p>)}</div></div></section>
  <section className="fb3-trust"><div className="fb3-wrap"><ShieldCheck size={38}/><div><p className="fb3-label">NO MAGIC ATTRIBUTION</p><h2>We will not pretend every sale has one perfect source.</h2><p>Fameboat works with what is known, calls out what is unclear, and makes the next investigation practical.</p></div></div></section>
  <section className="fb3-founder"><div className="fb3-wrap fb3-founder-grid"><div className="fb3-founder-icon">S</div><div><p className="fb3-label">FOUNDER</p><h2>Nearly two decades of asking the same business question.</h2><p>Shiva has worked across marketing, branding, media, digital and customer touchpoints. Fameboat is built around connecting fragmented signals to better everyday decisions.</p><span>Shiva · Founder, Fameboat</span></div></div></section>
  <section className="fb3-form"><div className="fb3-wrap fb3-form-grid"><div><p className="fb3-label">START YOUR AUDIT</p><h2>Before you spend more, understand what is already happening.</h2><p>14-Day Marketing Proof Audit · <strong>₹5,000</strong></p></div><form action="/#audit" onSubmit={submit}><input className="fb3-honeypot" name="company" tabIndex={-1} autoComplete="off"/><label>Name*<input name="name" required/></label><label>Business / Company*<input name="business" required/></label><label>Email*<input name="email" type="email" required/></label><label>Phone / WhatsApp*<input name="phone" required/></label><label className="wide">Website <em>(optional)</em><input name="website" placeholder="https://"/></label><label className="wide">What are you trying to understand?<textarea name="message" required/></label><button className="fb3-primary" disabled={status==="sending"}>{status==="sending"?"Sending…":"Request 14-Day Audit — ₹5,000"}<ArrowRight size={17}/></button>{message&&<p className={status==="success"?"success":"error"}>{message}</p>}</form></div></section>
  <footer><div className="fb3-wrap"><strong>Fameboat</strong><span>Evidence before assumptions.</span><Link href="/privacy">Privacy</Link></div></footer>
 </main>
}