import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'
import { StandardPage } from '@/components/CredibilitySite'

export const metadata:Metadata={title:'Digital Experience Sprint',description:'A focused engagement to clarify the business goal, improve the customer journey, and launch a practical digital experience.',alternates:{canonical:'/digital-credibility-sprint'}}
const stages=[['Stage 1','Review','Understand the business goal, audience, current experience, content, proof, and operational constraints.'],['Stage 2','Clarify','Define the message, customer journey, information structure, and the action the experience must support.'],['Stage 3','Design and Build','Create the agreed responsive experience, enquiry path, content structure, and practical supporting infrastructure.'],['Stage 4','Launch and Improve','Test devices and forms, configure measurement, deploy, hand over, and review the live experience.']]
const included=['Business and audience discovery','Positioning and message clarification','Current digital experience review','Customer journey architecture','Homepage, landing page, microsite, or agreed website scope','Clear service, programme, event, or offer presentation','Trust and credibility structure','Enquiry or action pathway','WhatsApp, email, form, or existing system handoff','Practical content-update workflow','Analytics and conversion-event setup','Mobile-first optimisation','Launch and post-launch review']
export default function Page(){return <StandardPage eyebrow="Focused paid engagement" title="Digital Experience Sprint" intro="A practical engagement to move from an unclear or disconnected digital presence to a focused customer experience built around one business goal."><section className="content-section"><div className="shell content-grid"><aside><p className="section-label">Who it is for</p><p className="lead-sm">For businesses whose online experience feels unclear, outdated, fragmented, difficult to operate, or disconnected from what customers need to do next.</p><Link className="button button-primary" href="/#review-lab">Start with the free review <ArrowRight size={17}/></Link></aside><div className="prose"><h2>A clear scope before implementation begins.</h2><p>The Sprint can support a focused website rebuild, landing experience, campaign, event microsite, publishing experience, or enquiry journey. Scope, timeline, and commercial terms depend on the outcome, content, complexity, and integrations required.</p><p>Fixed-scope engagements are priced after the review. The 21-day format is suitable for focused agreed projects. Larger or content-heavy requirements are divided into practical phases rather than forced into an unrealistic deadline.</p><div className="process-list">{stages.map(([time,title,text])=><article key={time}><span className="section-label">{time}</span><h3>{title}</h3><p>{text}</p></article>)}</div><h2>What may be included</h2><p>Deliverables are selected based on the business goal rather than sold as a fixed catalogue.</p><ul>{included.map(x=><li key={x}><Check size={15}/> {x}</li>)}</ul><h2>What the client provides</h2><p>Accurate business information, access to relevant systems, available content and brand assets, one decision-maker, and timely feedback during the engagement.</p><h2>What happens after launch</h2><p>Fameboat can support additional pages, campaign experiences, event microsites, publishing improvements, content support, and ongoing customer-experience optimisation where useful.</p><h2>What it does not include</h2><p>The Sprint is not a full CRM implementation, revenue-intelligence platform, executive dashboard, or open-ended business transformation programme. Those are outside Fameboat’s focused role.</p></div></div></section></StandardPage>}
