import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'
import { StandardPage } from '@/components/CredibilitySite'

export const metadata:Metadata={title:'Digital Credibility Sprint',description:'A focused 21-day engagement to clarify positioning, modernise the website, improve customer journeys, and launch a premium digital experience.',alternates:{canonical:'/digital-credibility-sprint'}}

const stages=[['Days 1–3','Understand','Review the business, audience, existing digital presence, credibility gaps, and customer journey.'],['Days 4–7','Clarify','Define positioning, key messages, information structure, proof, and conversion paths.'],['Days 8–17','Design and Build','Create the responsive digital experience, content structure, enquiry journeys, and supporting infrastructure.'],['Days 18–21','Test and Launch','Review the complete experience, test devices and forms, configure analytics, deploy, and hand over.']]
const included=['Business and audience discovery','Positioning and message clarification','Digital presence audit','Customer journey architecture','Premium homepage and agreed core website experience','Clear service, capability, or programme presentation','Trust and credibility structure','Qualified enquiry capture','Appropriate WhatsApp, email, or existing CRM handoff','Simple internal content-update workflow','Analytics and conversion-event setup','Mobile-first optimisation','Launch and post-launch review']

export default function Page(){return <StandardPage eyebrow="Focused productised service" title="Digital Credibility Sprint" intro="In 21 days, turn an outdated or unclear digital presence into a premium business experience built to earn trust and capture serious enquiries."><section className="content-section"><div className="shell content-grid"><aside><p className="section-label">Who it is for</p><p className="lead-sm">Established founder-led businesses whose real-world reputation, capabilities, or maturity are not represented clearly online.</p><Link className="button button-primary" href="/#review">Review My Digital Presence <ArrowRight size={17}/></Link></aside><div className="prose"><h2>A focused scope. A complete customer-facing experience.</h2><p>The sprint is designed for an agreed set of high-priority pages and journeys. It is not a promise that every large, content-heavy, or technically complex website can be completed in 21 days. Larger requirements are structured into clear phases.</p><div className="process-list">{stages.map(([time,title,text])=><article key={time}><span className="section-label">{time}</span><h3>{title}</h3><p>{text}</p></article>)}</div><h2>What may be included</h2><p>Deliverables depend on the business, available content, technical context, and agreed scope.</p><ul>{included.map(x=><li key={x}><Check size={15}/> {x}</li>)}</ul><h2>What the client provides</h2><p>Access to the current website and relevant accounts, accurate business information, available brand assets and proof, a clear decision-maker, and timely feedback during the sprint.</p><h2>What happens after launch</h2><p>Fameboat conducts a post-launch review and can support additional pages, campaign experiences, publishing support, event microsites, or ongoing digital experience improvements where useful.</p><h2>Outside the focused sprint</h2><p>Large custom software products, full CRM implementation, revenue dashboards, complex enterprise integrations, and open-ended transformation programmes are not part of the Digital Credibility Sprint.</p></div></div></section></StandardPage>}
