'use client'

import Link from 'next/link'
import { ChangeEvent, useMemo, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, BarChart3, Check, Download, FileCheck2, FileUp, RefreshCw, ShieldCheck, Sparkles, TrendingUp } from 'lucide-react'

type Row={channel:string;spend:number;interactions:number;enquiries:number;visits:number;customers:number;revenue:number;repeat:number;confidence:number}
type Template={label:string;objective:string;outcome:string;rows:Row[]}

const templates:Record<string,Template>={
 Restaurant:{label:'Restaurant / café',objective:'Increase visits and repeat customers',outcome:'Paying customers',rows:[{channel:'Google local',spend:20000,interactions:380,enquiries:74,visits:58,customers:42,revenue:68400,repeat:11,confidence:86},{channel:'Meta ads',spend:25000,interactions:720,enquiries:61,visits:36,customers:24,revenue:37600,repeat:4,confidence:58},{channel:'Creator',spend:15000,interactions:410,enquiries:35,visits:27,customers:18,revenue:42200,repeat:3,confidence:47},{channel:'WhatsApp',spend:5000,interactions:190,enquiries:48,visits:39,customers:32,revenue:51800,repeat:13,confidence:79}]},
 Interiors:{label:'Interiors / home improvement',objective:'Convert enquiries into site visits and projects',outcome:'Projects won',rows:[{channel:'Meta ads',spend:60000,interactions:940,enquiries:112,visits:24,customers:4,revenue:1420000,repeat:0,confidence:63},{channel:'Google search',spend:40000,interactions:310,enquiries:48,visits:19,customers:5,revenue:1870000,repeat:0,confidence:82},{channel:'Referrals',spend:12000,interactions:36,enquiries:28,visits:17,customers:6,revenue:2480000,repeat:0,confidence:91},{channel:'Instagram organic',spend:18000,interactions:680,enquiries:31,visits:7,customers:1,revenue:390000,repeat:0,confidence:41}]},
 Clinic:{label:'Clinic / wellness',objective:'Turn enquiries into attended appointments',outcome:'Attended appointments',rows:[{channel:'Google local',spend:35000,interactions:520,enquiries:128,visits:93,customers:76,revenue:304000,repeat:21,confidence:88},{channel:'Meta ads',spend:40000,interactions:960,enquiries:142,visits:71,customers:54,revenue:216000,repeat:9,confidence:61},{channel:'Referrals',spend:8000,interactions:58,enquiries:49,visits:43,customers:39,revenue:195000,repeat:18,confidence:93},{channel:'WhatsApp reactivation',spend:7000,interactions:220,enquiries:84,visits:62,customers:51,revenue:204000,repeat:36,confidence:84}]},
 Education:{label:'Education / admissions',objective:'Convert enquiries into applications and admissions',outcome:'Admissions',rows:[{channel:'Meta ads',spend:70000,interactions:1500,enquiries:260,visits:74,customers:18,revenue:1080000,repeat:0,confidence:66},{channel:'Google search',spend:50000,interactions:610,enquiries:132,visits:58,customers:22,revenue:1320000,repeat:0,confidence:84},{channel:'School outreach',spend:30000,interactions:210,enquiries:98,visits:51,customers:19,revenue:1140000,repeat:0,confidence:76},{channel:'Referrals',spend:15000,interactions:65,enquiries:54,visits:38,customers:21,revenue:1260000,repeat:0,confidence:92}]},
 Jewellery:{label:'Jewellery / premium retail',objective:'Connect campaigns with store visits and purchases',outcome:'Purchases',rows:[{channel:'Google local',spend:45000,interactions:680,enquiries:104,visits:76,customers:31,revenue:1860000,repeat:8,confidence:83},{channel:'Meta ads',spend:80000,interactions:1850,enquiries:176,visits:89,customers:27,revenue:1620000,repeat:5,confidence:59},{channel:'Creators',spend:65000,interactions:1320,enquiries:94,visits:54,customers:16,revenue:1280000,repeat:2,confidence:43},{channel:'Customer referrals',spend:12000,interactions:44,enquiries:39,visits:34,customers:23,revenue:2070000,repeat:11,confidence:94}]},
 Services:{label:'Agency / professional services',objective:'Move qualified leads into proposals and contracts',outcome:'Deals won',rows:[{channel:'LinkedIn',spend:25000,interactions:360,enquiries:42,visits:18,customers:5,revenue:620000,repeat:1,confidence:72},{channel:'Google search',spend:30000,interactions:240,enquiries:35,visits:17,customers:6,revenue:810000,repeat:2,confidence:84},{channel:'Founder network',spend:8000,interactions:52,enquiries:31,visits:19,customers:9,revenue:1350000,repeat:4,confidence:95},{channel:'Events',spend:22000,interactions:180,enquiries:28,visits:12,customers:3,revenue:360000,repeat:0,confidence:56}]},
 Other:{label:'Other business',objective:'Connect marketing activity with a real business outcome',outcome:'Customers or conversions',rows:[{channel:'Google',spend:30000,interactions:460,enquiries:82,visits:43,customers:24,revenue:216000,repeat:6,confidence:81},{channel:'Meta',spend:40000,interactions:980,enquiries:104,visits:47,customers:21,revenue:189000,repeat:3,confidence:57},{channel:'Referrals',spend:10000,interactions:54,enquiries:41,visits:31,customers:25,revenue:275000,repeat:8,confidence:92},{channel:'Offline / events',spend:20000,interactions:210,enquiries:36,visits:22,customers:12,revenue:132000,repeat:2,confidence:49}]}
}

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)
const number=(n:number)=>new Intl.NumberFormat('en-IN').format(Math.round(n))
const csvHeader='channel,spend,interactions,enquiries,visits,customers,revenue,repeat_customers,confidence'

function parseCSV(text:string):string[][]{
 const rows:string[][]=[];let row:string[]=[];let cell='';let quote=false
 for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1]
  if(ch==='"'&&quote&&next==='"'){cell+='"';i++;continue}
  if(ch==='"'){quote=!quote;continue}
  if(ch===','&&!quote){row.push(cell.trim());cell='';continue}
  if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';continue}
  cell+=ch
 }
 row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows
}

export default function ProofLab(){
 const[category,setCategory]=useState('Restaurant');const[custom,setCustom]=useState('');const[rows,setRows]=useState<Row[]>(templates.Restaurant.rows);const[source,setSource]=useState<'sample'|'csv'>('sample');const[fileName,setFileName]=useState('');const[error,setError]=useState('');const inputRef=useRef<HTMLInputElement>(null)
 const template=templates[category]||templates.Other
 const totals=useMemo(()=>rows.reduce((a,r)=>({spend:a.spend+r.spend,interactions:a.interactions+r.interactions,enquiries:a.enquiries+r.enquiries,visits:a.visits+r.visits,customers:a.customers+r.customers,revenue:a.revenue+r.revenue,repeat:a.repeat+r.repeat,confidence:a.confidence+r.confidence*r.customers}),{spend:0,interactions:0,enquiries:0,visits:0,customers:0,revenue:0,repeat:0,confidence:0}),[rows])
 const avgConfidence=totals.customers?Math.round(totals.confidence/totals.customers):0
 const best=useMemo(()=>[...rows].sort((a,b)=>(b.revenue/(b.spend||1))-(a.revenue/(a.spend||1)))[0], [rows])
 const weak=useMemo(()=>[...rows].sort((a,b)=>a.confidence-b.confidence)[0],[rows])
 const unknown=Math.round(rows.reduce((a,r)=>a+r.customers*(100-r.confidence)/100,0));const cac=totals.customers?totals.spend/totals.customers:0;const roas=totals.spend?totals.revenue/totals.spend:0
 const maxSpend=Math.max(...rows.map(r=>r.spend),1),maxRevenue=Math.max(...rows.map(r=>r.revenue),1)
 const choose=(key:string)=>{setCategory(key);setRows(templates[key].rows);setSource('sample');setFileName('');setError('');if(inputRef.current)inputRef.current.value=''}
 const onFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const matrix=parseCSV(await file.text());const heads=(matrix.shift()||[]).map(x=>x.trim().toLowerCase());const idx=(name:string)=>heads.indexOf(name);if(idx('channel')<0||idx('spend')<0||idx('customers')<0||idx('revenue')<0)throw new Error('Missing required columns');const parsed=matrix.filter(r=>r.some(Boolean)).map(c=>{const num=(name:string,fall=0)=>Number(String(c[idx(name)]??fall).replace(/[₹,$\s]/g,''))||0;return{channel:c[idx('channel')]||'Channel',spend:num('spend'),interactions:num('interactions'),enquiries:num('enquiries'),visits:num('visits'),customers:num('customers'),revenue:num('revenue'),repeat:num('repeat_customers'),confidence:Math.min(100,Math.max(0,num('confidence',60)))}});if(!parsed.length)throw new Error('No rows');setRows(parsed);setSource('csv');setFileName(file.name);setError('');requestAnimationFrame(()=>document.getElementById('campaign-dashboard')?.scrollIntoView({behavior:'smooth',block:'start'}))}catch{setError('We could not analyse that file. Keep the downloaded column names unchanged and use numbers only for metric fields.')}finally{if(inputRef.current)inputRef.current.value=''}}
 const download=()=>{const sample=template.rows.map(r=>[r.channel,r.spend,r.interactions,r.enquiries,r.visits,r.customers,r.revenue,r.repeat,r.confidence].join(',')).join('\n');const blob=new Blob([csvHeader+'\n'+sample],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`fameboat-${category.toLowerCase()}-sample.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
 return <div className="lab-site"><header className="lab-header"><div className="lab-shell lab-nav"><Link href="/" className="fb-brand"><span>F</span>Fameboat</Link><span>Campaign Proof Lab</span><Link href="/" className="lab-back"><ArrowLeft size={16}/> Back to Fameboat</Link></div></header><main>
  <section className="lab-hero"><div className="lab-shell"><div><h1>Upload marketing totals. See what created business.</h1><p>Choose your category, download its sample CSV, then upload the same file or replace it with your own aggregate numbers. The dashboard recalculates instantly in your browser.</p></div><div className="lab-trust"><ShieldCheck/>No customer-level data</div></div></section>
  <section className="lab-builder"><div className="lab-shell lab-builder-grid"><aside className="lab-controls"><div className="lab-step-label">Step 1</div><h2>Choose your business</h2><div className="lab-category-grid">{Object.entries(templates).map(([key,t])=><button key={key} className={category===key?'active':''} onClick={()=>choose(key)}>{t.label}</button>)}</div>{category==='Other'&&<label>Describe your business<input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="e.g. Pet care, auto service, manufacturing"/></label>}<div className="lab-context"><span>Sample objective</span><strong>{template.objective}</strong><span>Primary outcome</span><strong>{template.outcome}</strong></div><div className="lab-step-label">Step 2</div><h2>Download and inspect</h2><button className="lab-download" onClick={download}><Download size={16}/>Download {template.label} sample CSV</button><div className="lab-step-label">Step 3</div><h2>Upload and analyse</h2><p className="lab-small">Upload the downloaded sample to test the flow, or replace its rows with your own aggregate channel totals.</p><label className="lab-upload"><FileUp size={18}/>Choose CSV to analyse<input ref={inputRef} type="file" accept=".csv,text/csv" onChange={onFile}/></label>{fileName&&<div className="lab-file-success"><FileCheck2 size={17}/><div><strong>{fileName}</strong><span>Analysed successfully. Dashboard updated.</span></div></div>}{error&&<p className="lab-error">{error}</p>}<button className="lab-reset" onClick={()=>choose(category)}><RefreshCw size={15}/>Reset to category sample</button></aside>
  <div className="lab-results" id="campaign-dashboard"><div className="lab-results-head"><div><span>{source==='sample'?'Live synthetic example':'Uploaded aggregate data'}</span><h2>{category==='Other'&&custom?custom:template.label} intelligence</h2></div><em>{source==='sample'?'Illustrative':'Updated from CSV'}</em></div>
  <div className="lab-metrics"><Metric label="Marketing spend" value={money(totals.spend)} delta="Investment reviewed"/><Metric label="Customers / outcomes" value={number(totals.customers)} delta={`${totals.enquiries?Math.round(totals.customers/totals.enquiries*100):0}% enquiry conversion`}/><Metric label="Revenue linked" value={money(totals.revenue)} delta={`${roas.toFixed(1)}× revenue-to-spend`}/><Metric label="Cost per customer" value={money(Math.round(cac))} delta={`${avgConfidence}% evidence confidence`}/></div>
  <div className="lab-dashboard-grid"><section className="lab-panel lab-funnel-panel"><div className="lab-panel-title"><div><span>Customer movement</span><h3>Marketing-to-outcome funnel</h3></div><strong>{totals.interactions?((totals.customers/totals.interactions)*100).toFixed(1):'0'}% end conversion</strong></div><div className="lab-funnel-bars">{[['Interactions',totals.interactions,100],['Enquiries',totals.enquiries,totals.interactions?totals.enquiries/totals.interactions*100:0],['Visits / meetings',totals.visits,totals.interactions?totals.visits/totals.interactions*100:0],['Customers / outcomes',totals.customers,totals.interactions?totals.customers/totals.interactions*100:0]].map(([label,val,width])=><div key={String(label)}><div><span>{label}</span><strong>{number(Number(val))}</strong></div><i><b style={{width:`${Math.max(4,Number(width))}%`}}/></i></div>)}</div></section>
  <section className="lab-panel lab-confidence-panel"><div className="lab-panel-title"><div><span>Evidence quality</span><h3>Attribution confidence</h3></div></div><div className="lab-donut" style={{background:`conic-gradient(var(--lime) 0 ${avgConfidence}%,#27312b ${avgConfidence}% 100%)`}}><div><strong>{avgConfidence}%</strong><span>connected</span></div></div><div className="lab-confidence-copy"><p><strong>{Math.max(0,totals.customers-unknown)}</strong> outcomes have stronger source evidence.</p><p><strong>{unknown}</strong> remain influenced but not confidently assigned.</p></div></section></div>
  <section className="lab-panel"><div className="lab-panel-title"><div><span>Channel economics</span><h3>Spend versus linked revenue</h3></div><span>Bars update automatically after CSV upload</span></div><div className="lab-compare-chart">{rows.map(r=><article key={r.channel}><div className="lab-channel-name"><strong>{r.channel}</strong><span>{r.customers} outcomes · {r.confidence}% confidence</span></div><div className="lab-bars"><div><span>Spend</span><i><b style={{width:`${Math.max(3,r.spend/maxSpend*100)}%`}}/></i><strong>{money(r.spend)}</strong></div><div><span>Revenue</span><i><b style={{width:`${Math.max(3,r.revenue/maxRevenue*100)}%`}}/></i><strong>{money(r.revenue)}</strong></div></div></article>)}</div></section>
  <section className="lab-panel"><div className="lab-panel-title"><div><span>Performance map</span><h3>Efficiency and confidence by channel</h3></div></div><div className="lab-bubble-chart">{rows.map((r,i)=>{const efficiency=r.spend?r.revenue/r.spend:0;const maxEff=Math.max(...rows.map(x=>x.spend?x.revenue/x.spend:0),1);return <div key={r.channel} className="lab-bubble" style={{left:`${Math.min(91,Math.max(6,r.confidence))}%`,bottom:`${Math.min(84,Math.max(7,efficiency/maxEff*82))}%`,width:`${42+Math.min(42,r.customers)}px`,height:`${42+Math.min(42,r.customers)}px`,zIndex:i+1}} title={`${r.channel}: ${efficiency.toFixed(1)}× return, ${r.confidence}% confidence`}><span>{r.channel}</span></div>})}<div className="lab-axis-x">Low confidence <span/> High confidence</div><div className="lab-axis-y">Higher return</div></div></section>
  <div className="lab-insights"><article><TrendingUp/><div><span>Best current signal</span><strong>{best?.channel} shows the strongest linked revenue efficiency at {best?.spend?(best.revenue/best.spend).toFixed(1):'0'}×.</strong></div></article><article><Sparkles/><div><span>Evidence gap</span><strong>{unknown} outcomes remain only partially connected to a source. Improve capture before moving more budget.</strong></div></article><article><BarChart3/><div><span>Next experiment</span><strong>Retest {weak?.channel} with one unique link, offer code or source question and compare the result.</strong></div></article></div>
  <div className="lab-cta"><div><span>Your next step</span><h3>Want this dashboard designed around a real campaign?</h3><p>Start with public touchpoints and aggregate numbers. Deeper access is optional.</p></div><Link className="fb-btn fb-btn-primary" href="/#review">Discuss my campaign <ArrowRight size={18}/></Link></div></div></div></section>
 </main><footer className="lab-footer"><div className="lab-shell">Synthetic examples are for demonstration and do not represent client results. © 2026 Fameboat</div></footer></div>
}
function Metric({label,value,delta}:{label:string,value:string,delta:string}){return <div><span>{label}</span><strong>{value}</strong><small>{delta}</small></div>}
