'use client'

import Link from 'next/link'
import { ChangeEvent, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, BarChart3, Check, Download, FileUp, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react'

type Row={channel:string;spend:number;interactions:number;enquiries:number;visits:number;customers:number;revenue:number;repeat:number;confidence:number}
type Template={label:string;objective:string;outcome:string;rows:Row[]}

const templates:Record<string,Template>={
 Restaurant:{label:'Restaurant / café',objective:'Increase visits and repeat customers',outcome:'Paying customers',rows:[{channel:'Google local',spend:20000,interactions:380,enquiries:74,visits:58,customers:42,revenue:68400,repeat:11,confidence:86},{channel:'Meta ads',spend:25000,interactions:720,enquiries:61,visits:36,customers:24,revenue:37600,repeat:4,confidence:58},{channel:'Creator',spend:15000,interactions:410,enquiries:35,visits:27,customers:18,revenue:42200,repeat:3,confidence:47},{channel:'WhatsApp',spend:5000,interactions:190,enquiries:48,visits:39,customers:32,revenue:51800,repeat:13,confidence:79}]},
 Interiors:{label:'Interiors / home improvement',objective:'Convert enquiries into site visits and projects',outcome:'Projects won',rows:[{channel:'Meta ads',spend:60000,interactions:940,enquiries:112,visits:24,customers:4,revenue:1420000,repeat:0,confidence:63},{channel:'Google search',spend:40000,interactions:310,enquiries:48,visits:19,customers:5,revenue:1870000,repeat:0,confidence:82},{channel:'Referrals',spend:12000,interactions:36,enquiries:28,visits:17,customers:6,revenue:2480000,repeat:0,confidence:91},{channel:'Instagram organic',spend:18000,interactions:680,enquiries:31,visits:7,customers:1,revenue:390000,repeat:0,confidence:41}]},
 Clinic:{label:'Clinic / wellness',objective:'Turn enquiries into attended appointments',outcome:'Attended appointments',rows:[{channel:'Google local',spend:35000,interactions:520,enquiries:128,visits:93,customers:76,revenue:304000,repeat:21,confidence:88},{channel:'Meta ads',spend:40000,interactions:960,enquiries:142,visits:71,customers:54,revenue:216000,repeat:9,confidence:61},{channel:'Referrals',spend:8000,interactions:58,enquiries:49,visits:43,customers:39,revenue:195000,repeat:18,confidence:93},{channel:'WhatsApp reactivation',spend:7000,interactions:220,enquiries:84,visits:62,customers:51,revenue:204000,repeat:36,confidence:84}]},
 Education:{label:'Education / admissions',objective:'Convert enquiries into applications and admissions',outcome:'Admissions',rows:[{channel:'Meta ads',spend:70000,interactions:1500,enquiries:260,visits:74,customers:18,revenue:1080000,repeat:0,confidence:66},{channel:'Google search',spend:50000,interactions:610,enquiries:132,visits:58,customers:22,revenue:1320000,repeat:0,confidence:84},{channel:'School outreach',spend:30000,interactions:210,enquiries:98,visits:51,customers:19,revenue:1140000,repeat:0,confidence:76},{channel:'Referrals',spend:15000,interactions:65,enquiries:54,visits:38,customers:21,revenue:1260000,repeat:0,confidence:92}]},
 Jewellery:{label:'Jewellery / premium retail',objective:'Connect campaigns with store visits and purchases',outcome:'Purchases',rows:[{channel:'Google local',spend:45000,interactions:680,enquiries:104,visits:76,customers:31,revenue:1860000,repeat:8,confidence:83},{channel:'Meta ads',spend:80000,interactions:1850,enquiries:176,visits:89,customers:27,revenue:1620000,repeat:5,confidence:59},{channel:'Creators',spend:65000,interactions:1320,enquiries:94,visits:54,customers:16,revenue:1280000,repeat:2,confidence:43},{channel:'Customer referrals',spend:12000,interactions:44,enquiries:39,visits:34,customers:23,revenue:2070000,repeat:11,confidence:94}]},
 Services:{label:'Agency / professional services',objective:'Move qualified leads into proposals and contracts',outcome:'Deals won',rows:[{channel:'LinkedIn',spend:25000,interactions:360,enquiries:42,visits:18,customers:5,revenue:620000,repeat:1,confidence:72},{channel:'Google search',spend:30000,interactions:240,enquiries:35,visits:17,customers:6,revenue:810000,repeat:2,confidence:84},{channel:'Founder network',spend:8000,interactions:52,enquiries:31,visits:19,customers:9,revenue:1350000,repeat:4,confidence:95},{channel:'Events',spend:22000,interactions:180,enquiries:28,visits:12,customers:3,revenue:360000,repeat:0,confidence:56}]},
 Other:{label:'Other business',objective:'Connect marketing activity with a real business outcome',outcome:'Customers or conversions',rows:[{channel:'Google',spend:30000,interactions:460,enquiries:82,visits:43,customers:24,revenue:216000,repeat:6,confidence:81},{channel:'Meta',spend:40000,interactions:980,enquiries:104,visits:47,customers:21,revenue:189000,repeat:3,confidence:57},{channel:'Referrals',spend:10000,interactions:54,enquiries:41,visits:31,customers:25,revenue:275000,repeat:8,confidence:92},{channel:'Offline / events',spend:20000,interactions:210,enquiries:36,visits:22,customers:12,revenue:132000,repeat:2,confidence:49}]}
}
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)
const csvHeader='channel,spend,interactions,enquiries,visits,customers,revenue,repeat_customers,confidence'

export default function ProofLab(){
 const[category,setCategory]=useState('Restaurant');const[custom,setCustom]=useState('');const[rows,setRows]=useState<Row[]>(templates.Restaurant.rows);const[source,setSource]=useState<'sample'|'csv'>('sample');const[error,setError]=useState('')
 const template=templates[category]||templates.Other
 const totals=useMemo(()=>rows.reduce((a,r)=>({spend:a.spend+r.spend,interactions:a.interactions+r.interactions,enquiries:a.enquiries+r.enquiries,visits:a.visits+r.visits,customers:a.customers+r.customers,revenue:a.revenue+r.revenue,repeat:a.repeat+r.repeat}),{spend:0,interactions:0,enquiries:0,visits:0,customers:0,revenue:0,repeat:0}),[rows])
 const best=useMemo(()=>[...rows].sort((a,b)=>(b.customers/(b.spend||1))-(a.customers/(a.spend||1)))[0], [rows])
 const weak=useMemo(()=>[...rows].sort((a,b)=>a.confidence-b.confidence)[0],[rows])
 const unknown=Math.round(rows.reduce((a,r)=>a+r.customers*(100-r.confidence)/100,0));const cac=totals.customers?totals.spend/totals.customers:0;const roas=totals.spend?totals.revenue/totals.spend:0
 const choose=(key:string)=>{setCategory(key);setRows(templates[key].rows);setSource('sample');setError('')}
 const onFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();const lines=text.trim().split(/\r?\n/);const heads=lines.shift()?.split(',').map(x=>x.trim().toLowerCase())||[];const index=(name:string)=>heads.indexOf(name);if(index('channel')<0||index('spend')<0||index('customers')<0||index('revenue')<0)throw new Error('Missing required columns');const parsed=lines.filter(Boolean).map(line=>{const c=line.split(',').map(x=>x.trim());const num=(name:string,fall=0)=>Number(c[index(name)]||fall)||0;return{channel:c[index('channel')]||'Channel',spend:num('spend'),interactions:num('interactions'),enquiries:num('enquiries'),visits:num('visits'),customers:num('customers'),revenue:num('revenue'),repeat:num('repeat_customers'),confidence:Math.min(100,Math.max(0,num('confidence',60)))}});if(!parsed.length)throw new Error('No rows');setRows(parsed);setSource('csv');setError('')}catch{setError('We could not read that file. Use the downloadable aggregate template and keep the column names unchanged.')}}
 const download=()=>{const sample=templates[category].rows.map(r=>[r.channel,r.spend,r.interactions,r.enquiries,r.visits,r.customers,r.revenue,r.repeat,r.confidence].join(',')).join('\n');const blob=new Blob([csvHeader+'\n'+sample],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='fameboat-campaign-proof-template.csv';a.click();URL.revokeObjectURL(url)}
 return <div className="lab-site"><header className="lab-header"><div className="lab-shell lab-nav"><Link href="/" className="fb-brand"><span>F</span>Fameboat</Link><span>Campaign Proof Lab</span><Link href="/" className="lab-back"><ArrowLeft size={16}/> Back to Fameboat</Link></div></header><main>
  <section className="lab-hero"><div className="lab-shell"><div><h1>See what campaign proof could look like for your business.</h1><p>Choose a category to generate realistic synthetic data. No login, passwords or customer data. You can later test aggregate CSV totals entirely in your browser.</p></div><div className="lab-trust"><ShieldCheck/>Safe sample data first</div></div></section>
  <section className="lab-builder"><div className="lab-shell lab-builder-grid"><aside className="lab-controls"><h2>1. Choose your business</h2><div className="lab-category-grid">{Object.entries(templates).map(([key,t])=><button key={key} className={category===key?'active':''} onClick={()=>choose(key)}>{t.label}</button>)}</div>{category==='Other'&&<label>Describe your business<input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="e.g. Pet care, auto service, manufacturing"/></label>}<div className="lab-context"><span>Sample objective</span><strong>{template.objective}</strong><span>Primary outcome</span><strong>{template.outcome}</strong></div><button className="fb-btn fb-btn-dark" onClick={()=>{setRows(template.rows);setSource('sample')}}><RefreshCw size={16}/> Generate fresh sample</button><hr/><h2>2. Or use aggregate data</h2><p className="lab-small">No names, phone numbers or customer-level records. The file is read locally in your browser.</p><button className="lab-download" onClick={download}><Download size={16}/>Download CSV template</button><label className="lab-upload"><FileUp size={18}/>Upload aggregate CSV<input type="file" accept=".csv,text/csv" onChange={onFile}/></label>{error&&<p className="lab-error">{error}</p>}</aside>
  <div className="lab-results"><div className="lab-results-head"><div><span>{source==='sample'?'Synthetic example':'Your aggregate CSV'}</span><h2>{category==='Other'&&custom?custom:template.label} campaign proof</h2></div><em>{source==='sample'?'Illustrative':'Browser processed'}</em></div><div className="lab-metrics"><Metric label="Marketing spend" value={money(totals.spend)}/><Metric label="Customers / outcomes" value={String(totals.customers)}/><Metric label="Revenue linked" value={money(totals.revenue)}/><Metric label="Cost per customer" value={money(Math.round(cac))}/></div>
  <div className="lab-panel"><div className="lab-panel-title"><h3>Spend to business outcome</h3><span>{roas.toFixed(1)}× revenue-to-spend</span></div><div className="lab-funnel"><div><strong>{totals.interactions}</strong><span>Interactions</span></div><ArrowRight/><div><strong>{totals.enquiries}</strong><span>Enquiries</span></div><ArrowRight/><div><strong>{totals.visits}</strong><span>Visits / meetings</span></div><ArrowRight/><div><strong>{totals.customers}</strong><span>Customers / outcomes</span></div></div></div>
  <div className="lab-panel"><div className="lab-panel-title"><h3>Channel evidence</h3><span>Confidence reflects how well activity is connected to outcomes</span></div><div className="lab-channel-list">{rows.map(r=><article key={r.channel}><div><strong>{r.channel}</strong><span>{money(r.spend)} spend · {r.customers} outcomes · {money(r.revenue)} revenue</span></div><div className="lab-confidence"><i><b style={{width:`${r.confidence}%`}}/></i><span>{r.confidence}% confidence</span></div></article>)}</div></div>
  <div className="lab-insights"><article><Check/><div><span>What we know</span><strong>{best?.channel} currently produces the strongest identifiable outcome per rupee in this dataset.</strong></div></article><article><Sparkles/><div><span>What remains uncertain</span><strong>About {unknown} outcomes are influenced but not confidently connected to one source.</strong></div></article><article><BarChart3/><div><span>What to test next</span><strong>Retest {weak?.channel} with a unique link, offer code or source question before increasing spend.</strong></div></article></div>
  <div className="lab-cta"><div><span>Your next step</span><h3>Want this measurement designed around a real upcoming campaign?</h3><p>Start with public touchpoints and aggregate numbers. Deeper access is optional and earned after value is clear.</p></div><Link className="fb-btn fb-btn-primary" href="/#review">Discuss my campaign <ArrowRight size={18}/></Link></div></div></div></section>
 </main><footer className="lab-footer"><div className="lab-shell">Synthetic examples are for demonstration and do not represent client results. © 2026 Fameboat</div></footer></div>
}
function Metric({label,value}:{label:string,value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
