'use client'

import Link from 'next/link'
import { ChangeEvent, useMemo, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, BarChart3, Check, Download, FileCheck2, FileUp, Globe2, MapPin, RefreshCw, Rocket, ShieldCheck, Sparkles, Store, Target, TrendingUp } from 'lucide-react'

type Row={channel:string;spend:number;interactions:number;enquiries:number;visits:number;customers:number;revenue:number;repeat:number;confidence:number}
type Template={label:string;objective:string;outcome:string;rows:Row[];starter:string[];touchpoints:string[]}
type Mode='starting'|'existing'

const templates:Record<string,Template>={
 Restaurant:{label:'Restaurant / café',objective:'Increase visits and repeat customers',outcome:'Paying customers',starter:['Google Business Profile','Instagram starter page','Click-to-WhatsApp offer','Simple billing source question'],touchpoints:['Local discovery','Offer view','WhatsApp / call','Store visit','Bill / repeat'],rows:[{channel:'Google local',spend:20000,interactions:380,enquiries:74,visits:58,customers:42,revenue:68400,repeat:11,confidence:86},{channel:'Meta ads',spend:25000,interactions:720,enquiries:61,visits:36,customers:24,revenue:37600,repeat:4,confidence:58},{channel:'Creator',spend:15000,interactions:410,enquiries:35,visits:27,customers:18,revenue:42200,repeat:3,confidence:47},{channel:'WhatsApp',spend:5000,interactions:190,enquiries:48,visits:39,customers:32,revenue:51800,repeat:13,confidence:79}]},
 Interiors:{label:'Interiors / home improvement',objective:'Convert enquiries into site visits and projects',outcome:'Projects won',starter:['One-page project portfolio','Google Business Profile','Trackable enquiry form','Site-visit and quotation tracker'],touchpoints:['Discovery','Enquiry','Qualification','Site visit','Quotation / project'],rows:[{channel:'Meta ads',spend:60000,interactions:940,enquiries:112,visits:24,customers:4,revenue:1420000,repeat:0,confidence:63},{channel:'Google search',spend:40000,interactions:310,enquiries:48,visits:19,customers:5,revenue:1870000,repeat:0,confidence:82},{channel:'Referrals',spend:12000,interactions:36,enquiries:28,visits:17,customers:6,revenue:2480000,repeat:0,confidence:91},{channel:'Instagram organic',spend:18000,interactions:680,enquiries:31,visits:7,customers:1,revenue:390000,repeat:0,confidence:41}]},
 Clinic:{label:'Clinic / wellness',objective:'Turn enquiries into attended appointments',outcome:'Attended appointments',starter:['Google profile and reviews','Service / doctor landing page','Appointment WhatsApp flow','Visit and repeat tracking'],touchpoints:['Search / referral','Enquiry','Appointment','Visit','Treatment / repeat'],rows:[{channel:'Google local',spend:35000,interactions:520,enquiries:128,visits:93,customers:76,revenue:304000,repeat:21,confidence:88},{channel:'Meta ads',spend:40000,interactions:960,enquiries:142,visits:71,customers:54,revenue:216000,repeat:9,confidence:61},{channel:'Referrals',spend:8000,interactions:58,enquiries:49,visits:43,customers:39,revenue:195000,repeat:18,confidence:93},{channel:'WhatsApp reactivation',spend:7000,interactions:220,enquiries:84,visits:62,customers:51,revenue:204000,repeat:36,confidence:84}]},
 Education:{label:'Education / admissions',objective:'Convert enquiries into applications and admissions',outcome:'Admissions',starter:['Clear programme landing page','Counselling booking flow','Source-tagged enquiry form','Admission pipeline tracker'],touchpoints:['Discovery','Enquiry','Counselling','Application','Admission'],rows:[{channel:'Meta ads',spend:70000,interactions:1500,enquiries:260,visits:74,customers:18,revenue:1080000,repeat:0,confidence:66},{channel:'Google search',spend:50000,interactions:610,enquiries:132,visits:58,customers:22,revenue:1320000,repeat:0,confidence:84},{channel:'School outreach',spend:30000,interactions:210,enquiries:98,visits:51,customers:19,revenue:1140000,repeat:0,confidence:76},{channel:'Referrals',spend:15000,interactions:65,enquiries:54,visits:38,customers:21,revenue:1260000,repeat:0,confidence:92}]},
 Jewellery:{label:'Jewellery / premium retail',objective:'Connect campaigns with store visits and purchases',outcome:'Purchases',starter:['Google store presence','Occasion-led landing page','Store-visit offer code','New / repeat buyer capture'],touchpoints:['Discovery','Collection view','Enquiry','Store visit','Purchase / repeat'],rows:[{channel:'Google local',spend:45000,interactions:680,enquiries:104,visits:76,customers:31,revenue:1860000,repeat:8,confidence:83},{channel:'Meta ads',spend:80000,interactions:1850,enquiries:176,visits:89,customers:27,revenue:1620000,repeat:5,confidence:59},{channel:'Creators',spend:65000,interactions:1320,enquiries:94,visits:54,customers:16,revenue:1280000,repeat:2,confidence:43},{channel:'Customer referrals',spend:12000,interactions:44,enquiries:39,visits:34,customers:23,revenue:2070000,repeat:11,confidence:94}]},
 Services:{label:'Agency / professional services',objective:'Move qualified leads into proposals and contracts',outcome:'Deals won',starter:['Focused offer landing page','Founder credibility page','Discovery-call booking','Proposal and follow-up tracker'],touchpoints:['Discovery','Lead','Discovery call','Proposal','Contract'],rows:[{channel:'LinkedIn',spend:25000,interactions:360,enquiries:42,visits:18,customers:5,revenue:620000,repeat:1,confidence:72},{channel:'Google search',spend:30000,interactions:240,enquiries:35,visits:17,customers:6,revenue:810000,repeat:2,confidence:84},{channel:'Founder network',spend:8000,interactions:52,enquiries:31,visits:19,customers:9,revenue:1350000,repeat:4,confidence:95},{channel:'Events',spend:22000,interactions:180,enquiries:28,visits:12,customers:3,revenue:360000,repeat:0,confidence:56}]},
 Other:{label:'Other business',objective:'Create a measurable path from first discovery to customer',outcome:'Customers or conversions',starter:['Clear online presence','One primary call to action','Trackable enquiry path','Simple outcome tracker'],touchpoints:['Discovery','Interest','Enquiry','Visit / meeting','Customer'],rows:[{channel:'Google',spend:30000,interactions:460,enquiries:82,visits:43,customers:24,revenue:216000,repeat:6,confidence:81},{channel:'Meta',spend:40000,interactions:980,enquiries:104,visits:47,customers:21,revenue:189000,repeat:3,confidence:57},{channel:'Referrals',spend:10000,interactions:54,enquiries:41,visits:31,customers:25,revenue:275000,repeat:8,confidence:92},{channel:'Offline / events',spend:20000,interactions:210,enquiries:36,visits:22,customers:12,revenue:132000,repeat:2,confidence:49}]}
}

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)
const number=(n:number)=>new Intl.NumberFormat('en-IN').format(Math.round(n))
const csvHeader='channel,spend,interactions,enquiries,visits,customers,revenue,repeat_customers,confidence'
const budgets=[15000,30000,50000,100000]

function parseCSV(text:string):string[][]{const rows:string[][]=[];let row:string[]=[];let cell='';let quote=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quote&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quote=!quote;continue}if(ch===','&&!quote){row.push(cell.trim());cell='';continue}if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';continue}cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}

export default function ProofLab(){
 const[mode,setMode]=useState<Mode>('starting');const[category,setCategory]=useState('Restaurant');const[custom,setCustom]=useState('');const[goal,setGoal]=useState('Get first customers');const[budget,setBudget]=useState(30000);const[rows,setRows]=useState<Row[]>(templates.Restaurant.rows);const[source,setSource]=useState<'sample'|'csv'|'plan'>('plan');const[fileName,setFileName]=useState('');const[error,setError]=useState('');const inputRef=useRef<HTMLInputElement>(null)
 const template=templates[category]||templates.Other
 const plannedRows=useMemo(()=>{const base=template.rows.reduce((a,r)=>a+r.spend,0)||1;return template.rows.map(r=>{const share=r.spend/base;const scale=budget/base;return{...r,spend:Math.round(budget*share),interactions:Math.max(20,Math.round(r.interactions*scale*.85)),enquiries:Math.max(3,Math.round(r.enquiries*scale*.8)),visits:Math.max(1,Math.round(r.visits*scale*.72)),customers:Math.max(1,Math.round(r.customers*scale*.65)),revenue:Math.max(0,Math.round(r.revenue*scale*.6)),repeat:Math.max(0,Math.round(r.repeat*scale*.5)),confidence:Math.max(35,Math.min(82,r.confidence-8))}})},[template,budget])
 const activeRows=mode==='starting'?plannedRows:rows
 const totals=useMemo(()=>activeRows.reduce((a,r)=>({spend:a.spend+r.spend,interactions:a.interactions+r.interactions,enquiries:a.enquiries+r.enquiries,visits:a.visits+r.visits,customers:a.customers+r.customers,revenue:a.revenue+r.revenue,repeat:a.repeat+r.repeat,confidence:a.confidence+r.confidence*r.customers}),{spend:0,interactions:0,enquiries:0,visits:0,customers:0,revenue:0,repeat:0,confidence:0}),[activeRows])
 const avgConfidence=totals.customers?Math.round(totals.confidence/totals.customers):0
 const best=useMemo(()=>[...activeRows].sort((a,b)=>(b.revenue/(b.spend||1))-(a.revenue/(a.spend||1)))[0],[activeRows])
 const weak=useMemo(()=>[...activeRows].sort((a,b)=>a.confidence-b.confidence)[0],[activeRows])
 const unknown=Math.round(activeRows.reduce((a,r)=>a+r.customers*(100-r.confidence)/100,0));const cac=totals.customers?totals.spend/totals.customers:0;const roas=totals.spend?totals.revenue/totals.spend:0
 const maxSpend=Math.max(...activeRows.map(r=>r.spend),1),maxRevenue=Math.max(...activeRows.map(r=>r.revenue),1)
 const readiness=mode==='starting'?18:Math.min(92,45+(fileName?28:10))
 const choose=(key:string)=>{setCategory(key);setRows(templates[key].rows);setSource(mode==='starting'?'plan':'sample');setFileName('');setError('');if(inputRef.current)inputRef.current.value=''}
 const onFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const matrix=parseCSV(await file.text());const heads=(matrix.shift()||[]).map(x=>x.trim().toLowerCase());const idx=(name:string)=>heads.indexOf(name);if(idx('channel')<0||idx('spend')<0||idx('customers')<0||idx('revenue')<0)throw new Error('Missing required columns');const parsed=matrix.filter(r=>r.some(Boolean)).map(c=>{const num=(name:string,fall=0)=>Number(String(c[idx(name)]??fall).replace(/[₹,$\s]/g,''))||0;return{channel:c[idx('channel')]||'Channel',spend:num('spend'),interactions:num('interactions'),enquiries:num('enquiries'),visits:num('visits'),customers:num('customers'),revenue:num('revenue'),repeat:num('repeat_customers'),confidence:Math.min(100,Math.max(0,num('confidence',60)))}});if(!parsed.length)throw new Error('No rows');setMode('existing');setRows(parsed);setSource('csv');setFileName(file.name);setError('');requestAnimationFrame(()=>document.getElementById('campaign-dashboard')?.scrollIntoView({behavior:'smooth',block:'start'}))}catch{setError('We could not analyse that file. Keep the downloaded column names unchanged and use numbers only for metric fields.')}finally{if(inputRef.current)inputRef.current.value=''}}
 const download=()=>{const sample=template.rows.map(r=>[r.channel,r.spend,r.interactions,r.enquiries,r.visits,r.customers,r.revenue,r.repeat,r.confidence].join(',')).join('\n');const blob=new Blob([csvHeader+'\n'+sample],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`fameboat-${category.toLowerCase()}-sample.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
 const switchMode=(next:Mode)=>{setMode(next);setSource(next==='starting'?'plan':'sample');setFileName('');setError('')}
 return <div className="lab-site"><header className="lab-header"><div className="lab-shell lab-nav"><Link href="/" className="fb-brand"><span>F</span>Fameboat</Link><span>Growth & Campaign Proof Lab</span><Link href="/" className="lab-back"><ArrowLeft size={16}/> Back to Fameboat</Link></div></header><main>
  <section className="lab-hero"><div className="lab-shell"><div><h1>Start from zero—or understand what your campaigns are creating.</h1><p>No website, no ads and no past data? Fameboat can still show the first measurable path. Already marketing? Upload aggregate totals and see the evidence change instantly.</p></div><div className="lab-trust"><ShieldCheck/>No customer-level data</div></div></section>
  <section className="lab-mode-wrap"><div className="lab-shell lab-mode-switch"><button className={mode==='starting'?'active':''} onClick={()=>switchMode('starting')}><Rocket/><span><strong>I am starting from zero</strong><small>No campaigns or online presence yet</small></span></button><button className={mode==='existing'?'active':''} onClick={()=>switchMode('existing')}><BarChart3/><span><strong>I already run campaigns</strong><small>Use sample or aggregate CSV data</small></span></button></div></section>
  <section className="lab-builder"><div className="lab-shell lab-builder-grid"><aside className="lab-controls"><div className="lab-step-label">Step 1</div><h2>Choose your business</h2><div className="lab-category-grid">{Object.entries(templates).map(([key,t])=><button key={key} className={category===key?'active':''} onClick={()=>choose(key)}>{t.label}</button>)}</div>{category==='Other'&&<label>Describe your business<input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="e.g. Pet care, auto service, manufacturing"/></label>}
  {mode==='starting'?<><div className="lab-step-label">Step 2</div><h2>Choose your first goal</h2><select className="lab-select" value={goal} onChange={e=>setGoal(e.target.value)}><option>Get first customers</option><option>Generate enquiries</option><option>Drive visits or appointments</option><option>Launch a new service</option><option>Build local awareness</option></select><div className="lab-step-label">Step 3</div><h2>Set a test budget</h2><div className="lab-budget-grid">{budgets.map(x=><button key={x} className={budget===x?'active':''} onClick={()=>setBudget(x)}>{money(x)}</button>)}</div><p className="lab-small">This creates an illustrative first-growth plan—not a revenue guarantee.</p></>:<><div className="lab-context"><span>Sample objective</span><strong>{template.objective}</strong><span>Primary outcome</span><strong>{template.outcome}</strong></div><div className="lab-step-label">Step 2</div><h2>Download and inspect</h2><button className="lab-download" onClick={download}><Download size={16}/>Download {template.label} sample CSV</button><div className="lab-step-label">Step 3</div><h2>Upload and analyse</h2><p className="lab-small">Upload the downloaded sample or replace it with your own aggregate channel totals.</p><label className="lab-upload"><FileUp size={18}/>Choose CSV to analyse<input ref={inputRef} type="file" accept=".csv,text/csv" onChange={onFile}/></label>{fileName&&<div className="lab-file-success"><FileCheck2 size={17}/><div><strong>{fileName}</strong><span>Analysed successfully. Dashboard updated.</span></div></div>}{error&&<p className="lab-error">{error}</p>}<button className="lab-reset" onClick={()=>choose(category)}><RefreshCw size={15}/>Reset to category sample</button></>}</aside>
  <div className="lab-results" id="campaign-dashboard"><div className="lab-results-head"><div><span>{mode==='starting'?'Illustrative first-growth plan':source==='csv'?'Uploaded aggregate data':'Live synthetic example'}</span><h2>{category==='Other'&&custom?custom:template.label} {mode==='starting'?'launch blueprint':'intelligence'}</h2></div><em>{mode==='starting'?'Start from zero':source==='csv'?'Updated from CSV':'Illustrative'}</em></div>
  {mode==='starting'&&<><div className="lab-zero-summary"><div><span>Selected goal</span><strong>{goal}</strong></div><div><span>Test budget</span><strong>{money(budget)}</strong></div><div><span>Current digital readiness</span><strong>{readiness}/100</strong></div><div><span>Primary outcome</span><strong>{template.outcome}</strong></div></div><section className="lab-panel lab-start-stack"><div className="lab-panel-title"><div><span>Build before promotion</span><h3>Your minimum measurable growth stack</h3></div><strong>4 essentials</strong></div><div className="lab-starter-grid">{template.starter.map((item,i)=><article key={item}><span>0{i+1}</span>{i===0?<Globe2/>:i===1?<Store/>:i===2?<Target/>:<BarChart3/>}<strong>{item}</strong></article>)}</div></section><section className="lab-panel"><div className="lab-panel-title"><div><span>Customer journey</span><h3>What Fameboat would make measurable first</h3></div></div><div className="lab-touchpoint-flow">{template.touchpoints.map((x,i)=><div key={x}><span>{i+1}</span><strong>{x}</strong>{i<template.touchpoints.length-1&&<ArrowRight/>}</div>)}</div></section></>}
  <div className="lab-metrics"><Metric label={mode==='starting'?'Suggested test budget':'Marketing spend'} value={money(totals.spend)} delta={mode==='starting'?'Controlled first experiment':'Investment reviewed'}/><Metric label={mode==='starting'?'Illustrative outcomes':'Customers / outcomes'} value={number(totals.customers)} delta={`${totals.enquiries?Math.round(totals.customers/totals.enquiries*100):0}% enquiry conversion`}/><Metric label={mode==='starting'?'Illustrative linked value':'Revenue linked'} value={money(totals.revenue)} delta={`${roas.toFixed(1)}× value-to-spend`}/><Metric label="Cost per outcome" value={money(Math.round(cac))} delta={`${avgConfidence}% projected evidence confidence`}/></div>
  <div className="lab-dashboard-grid"><section className="lab-panel lab-funnel-panel"><div className="lab-panel-title"><div><span>{mode==='starting'?'Projected customer movement':'Customer movement'}</span><h3>Discovery-to-outcome funnel</h3></div><strong>{totals.interactions?((totals.customers/totals.interactions)*100).toFixed(1):'0'}% end conversion</strong></div><div className="lab-funnel-bars">{[['Interactions',totals.interactions,100],['Enquiries',totals.enquiries,totals.interactions?totals.enquiries/totals.interactions*100:0],['Visits / meetings',totals.visits,totals.interactions?totals.visits/totals.interactions*100:0],['Customers / outcomes',totals.customers,totals.interactions?totals.customers/totals.interactions*100:0]].map(([label,val,width])=><div key={String(label)}><div><span>{label}</span><strong>{number(Number(val))}</strong></div><i><b style={{width:`${Math.max(4,Number(width))}%`}}/></i></div>)}</div></section><section className="lab-panel lab-confidence-panel"><div className="lab-panel-title"><div><span>{mode==='starting'?'Measurement design':'Evidence quality'}</span><h3>{mode==='starting'?'Proof potential':'Attribution confidence'}</h3></div></div><div className="lab-donut" style={{background:`conic-gradient(var(--lime) 0 ${avgConfidence}%,#27312b ${avgConfidence}% 100%)`}}><div><strong>{avgConfidence}%</strong><span>{mode==='starting'?'possible':'connected'}</span></div></div><div className="lab-confidence-copy"><p><strong>{Math.max(0,totals.customers-unknown)}</strong> outcomes could carry stronger source evidence.</p><p><strong>{unknown}</strong> may still remain influenced but uncertain.</p></div></section></div>
  <section className="lab-panel"><div className="lab-panel-title"><div><span>{mode==='starting'?'Suggested channel mix':'Channel economics'}</span><h3>{mode==='starting'?'How the first test budget could be allocated':'Spend versus linked revenue'}</h3></div><span>{mode==='starting'?'Illustrative planning model':'Updates automatically after CSV upload'}</span></div><div className="lab-compare-chart">{activeRows.map(r=><article key={r.channel}><div className="lab-channel-name"><strong>{r.channel}</strong><span>{r.customers} outcomes · {r.confidence}% confidence</span></div><div className="lab-bars"><div><span>Spend</span><i><b style={{width:`${Math.max(3,r.spend/maxSpend*100)}%`}}/></i><strong>{money(r.spend)}</strong></div><div><span>Value</span><i><b style={{width:`${Math.max(3,r.revenue/maxRevenue*100)}%`}}/></i><strong>{money(r.revenue)}</strong></div></div></article>)}</div></section>
  {mode==='starting'&&<section className="lab-panel"><div className="lab-panel-title"><div><span>30-day start plan</span><h3>What happens before and after launch</h3></div></div><div className="lab-roadmap">{[['Week 1','Create the minimum online presence and one clear offer.'],['Week 2','Install trackable enquiry, WhatsApp, booking or visit paths.'],['Week 3','Run one controlled local campaign with a defined outcome.'],['Week 4','Compare spend, enquiries, visits and customers; decide what to continue.']].map(([w,t],i)=><article key={w}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{w}</strong><p>{t}</p></div></article>)}</div></section>}
  <div className="lab-insights"><article><TrendingUp/><div><span>{mode==='starting'?'Best place to begin':'Best current signal'}</span><strong>{mode==='starting'?`${best?.channel} is the strongest first test in this illustrative plan.`:`${best?.channel} shows the strongest linked revenue efficiency at ${best?.spend?(best.revenue/best.spend).toFixed(1):'0'}×.`}</strong></div></article><article><Sparkles/><div><span>{mode==='starting'?'Build before ads':'Evidence gap'}</span><strong>{mode==='starting'?'Create source capture and one clear conversion path before spending heavily.':`${unknown} outcomes remain only partially connected to a source.`}</strong></div></article><article><MapPin/><div><span>Next experiment</span><strong>{mode==='starting'?`Run one local test for ${goal.toLowerCase()} and measure the complete journey.`:`Retest ${weak?.channel} with one unique link, offer code or source question.`}</strong></div></article></div>
  <div className="lab-cta"><div><span>Your next step</span><h3>{mode==='starting'?'Want Fameboat to build your first measurable growth system?':'Want this dashboard designed around a real campaign?'}</h3><p>{mode==='starting'?'Start with your business, offer and first customer path. No existing campaign data required.':'Start with public touchpoints and aggregate numbers. Deeper access is optional.'}</p></div><Link className="fb-btn fb-btn-primary" href="/#review">{mode==='starting'?'Plan my first growth system':'Discuss my campaign'} <ArrowRight size={18}/></Link></div></div></div></section>
 </main><footer className="lab-footer"><div className="lab-shell">Planning projections and synthetic examples are illustrative and do not represent guaranteed or client results. © 2026 Fameboat</div></footer></div>
}
function Metric({label,value,delta}:{label:string,value:string,delta:string}){return <div><span>{label}</span><strong>{value}</strong><small>{delta}</small></div>}
